#!/bin/bash
clear
# update vps
    
# domain
read -rp "Masukan Domain :" domain
# buat folder xray
    mkdir -p /etc/xray
    mkdir -p /var/log/xray
    chmod +x /var/log/xray
    echo "${domain}" >/etc/xray/domain
    touch /var/log/xray/access.log
    touch /var/log/xray/error.log
# install sertifikat
    
# install xray
    apt install nginx -y
    bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install -u www-data --version 1.6.5
    wget -O /etc/xray/config.json "https://github.com/axcellsz/gas/raw/main/file/config.json"
    rm -rf /etc/systemd/system/xray.service.d
    cat >/etc/systemd/system/xray.service <<EOF
Description=Xray Service
Documentation=https://github.com/xtls
After=network.target nss-lookup.target

[Service]
User=www-data
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=/usr/local/bin/xray run -config /etc/xray/config.json
Restart=on-failure
RestartPreventExitStatus=23
LimitNPROC=10000
LimitNOFILE=1000000

[Install]
WantedBy=multi-user.target

EOF
  cat >/root/.profile <<END
# ~/.profile: executed by Bourne-compatible login shells.
if [ "$BASH" ]; then
  if [ -f ~/.bashrc ]; then
    . ~/.bashrc
  fi
fi
mesg n || true
cmenu
END
chmod 644 /root/.profile
  cat >/etc/cron.d/xp_all <<-END
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
2 0 * * * root /usr/bin/xp
END
# file menu
    cd
    rm -rf *
    rm /var/www/html/*.html
    rm /etc/nginx/sites-enabled/default
    rm /etc/nginx/sites-available/default
wget -O /usr/bin/xp https://github.com/axcellsz/sec/raw/main/file/xp && chmod +x /usr/bin/xp
wget -O /etc/nginx/nginx.conf https://github.com/axcellsz/sec/raw/main/file/nginx.conf
wget -O /etc/nginx/conf.d/xray.conf https://github.com/axcellsz/sec/raw/main/file/xray.conf
systemctl daemon-reload
systemctl restart nginx
systemctl restart xray
echo "Install Selesai"
sleep 2
clear
menu
