#!/bin/bash
clear
read -rp "Domain/Host : " -e domain
rm -rf /etc/xray/domain
echo $domain > /etc/xray/domain
echo -e "selesai"
echo -e " "
read -n 1 -s -r -p "Press any key to back on menu"

set-cmenu
