#!/bin/bash
clear
GRB="\e[92;1m"
NCO='\033[0m'
RED='\033[0;31m'
TB

IPX=$(curl -s ipv4.icanhazip.com)
DOM=$(cat /etc/xray/domain)

if [[ $nginx == "running" ]]; then
    status_server="${GRB}[ON]${NCO}"
else
    status_server="${RED}[OFF]${NCO}"
fi

echo -e " ${NCO}Ip / Host   : ${GRB}$IPX / $DOM"
echo -e " ${NCO}X-ray Status  ${GRB}$status_server           t.me/axsystem"
echo -e "==================================================="
   
$NC\e[032;1mIp / Host :\e[0m \e[1m$IPX\e[0m
$NC\e[032;1mXray Status :\e[0m \e[1m$status_server\e[0m
echo -e "==================================================="
