#!/bin/bash
clear
GRB="\e[92;1m"
NCO='\033[0m'
RED='\033[0;31m'

if [[ $nginx == "running" ]]; then
    status_server="${GRB}Online ✔${NCO}"
else
    status_server="${RED}Offline ✖${NCO}"
fi

echo -e " Server Xray Status:" $status_server
