#!/bin/bash
clear
GRB="\e[92;1m"
NCO='\033[0m'
RED='\033[0;31m'
YEL='\033[0;33m'

IPX=$(curl -s ipv4.icanhazip.com)
DOM=$(cat /etc/xray/domain)

if [[ $nginx == "running" ]]; then
    status_server="${GRB}[ON]${NCO}"
else
    status_server="${RED}[OFF]${NCO}"
fi
echo -e " ${NCO}Host   :  ${GRB}$DOM"
echo -e " ${NCO}IP : ${GRB}$IPX
echo -e " ${NCO}X-ray Status  ${GRB}$status_server"
echo -e " ${YEL}Script by Axnet
echo -e "${NCO}"
echo -e "1. MENU"
echo -e "1. SETTING"
