#!/bin/bash
clear
echo -e "1. VMESS AKRAB"
echo -e "2. VMESS FLEX"
echo -e "3. VMESS MANUAL BUG"
echo -e "4. VMESS DEFAULT"
echo -e "5. ATUR AKUN
echo -e "6. SETTING"
echo -e "7. RESTART XRAY"
echo -e "8. REBOOT VPS"
read -p "Select From Options :  " menu
case $menu in 
1)
vms-akb
;;
2)
vms-flx
;;
3)
vms-def
;;
4)
vms-man
;;
5)
set-akun
;;
6)
set-cmenu
;;
7)
systemctl daemon-reload
systemctl restart nginx
systemctl restart xray
echo -e "SELESAI.."
sleep 2
clear
menu
;;
8)
reboot
;;
*)
echo "Input The Correct Number !"
clear
menu
;;
esac
