#!/bin/bash
clear
echo -e "1. GANTI DOMAIN"
echo -e "2. PERBARUI SERTIFIKAT"
echo -e "3. RUBAH PORT"
echo -e "4. KEMBALI"
echo -e " "
read -p "Select From Options :  " menu
case $menu in 
1)
ad-dom
;;
2)
ad-cert
;;
3)
set-port
;;
4)
menu
;;
*)
echo "Input The Correct Number !"
clear
set-cmenu
;;
esac
