#!/bin/bash
clear
echo -e "1. GANTI DOMAIN"
echo -e "2. PERBARUI SERTIFIKAT"
echo -e "3. RUBAH PORT"
echo -e "3. KEMBALI"
read -p "     Select From Options :  " vvv
case $vvv in 
1)
add-domain
;;
2)
cert
;;
3)
set-port
;;
4)
menu
;;
*)
echo "Input The Correct Number !"
;;
esac
