#!/bin/bash
clear
echo -e "1. GANTI DOMAIN"
echo -e "2. PERBARUI SERTIFIKAT"
echo -e "3. RUBAH PORT"
echo -e "3. KEMBALI"
read -p "     Select From Options :  " cmenu
case $cmenu in 
1)
ad-dom
;;
2)
ad-cert
;;
3)
set-port
;;
4)
cmenu
;;
*)
echo "Input The Correct Number !"
;;
esac
